version: '3.8'

services:
  fastapi_app:
    build: .
    ports:
      - "6969:6969"
    volumes:
      - .:/app
    environment:
      - ENV=.env

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./app:/app
    ports:
      - "80:80"
    depends_on:
      - fastapi_app
